[profile.default]
src = 'src'
out = 'out'
libs = ['node_modules', 'lib']
# viaIR = true
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@chainlink/=lib/chainlink",
    "@chainlink2/contracts-ccip/=lib/ccip-contracts/contracts-ccip/",
    "@ccip-contracts/=lib/ccip-contracts/",
    '@chainlink/contracts-ccip/=lib/ccip-contracts/contracts-ccip/',
    '@chainlink-brownie-contracts/=lib/chainlink/'
]

fs_permissions = [{ access = "read", path = "./" }]
evm_version = "cancun"


[etherscan]
ethereum = { key = "${ETHERSCAN_API_KEY}" } 
ethereumSepolia = { key = "${ETHERSCAN_API_KEY}" }
base = { key = "${BASESCAN_API_KEY}" }
baseSepolia = { key = "${BASESCAN_API_KEY}" }
polygon = { key = "${POLYGONSCAN_API_KEY}" }
polygonAmoy = { key = "${POLYGONSCAN_API_KEY}" }


[rpc_endpoints]
ethereum = "${ETHEREUM_RPC_URL}"
ethereumSepolia = "${ETHEREUM_SEPOLIA_RPC_URL}"
base = "${BASE_RPC_URL}"
baseSepolia = "${BASE_SEPOLIA_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
polygonAmoy = "${POLYGON_AMOY_RPC_URL}"

[invariant]
runs = 64
depth = 64
fail_on_revert = true

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
